name: CI
on: push
env:
  NEXT_PUBLIC_CLOUD_NAME: dlas6lasm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install
      - name: Run tests
        run: pnpm test
